package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/GaelLnz/goya/api/graphql/model"
)

// Would've been great to use uint here, but for some reason gqlgen seems to do a poor job at handling them. Negative numbers passed to uint do NOT result in an API error. I have no time to investigate further. More here https://gqlgen.com/reference/scalars/
func (r *queryResolver) BonusMalusScore(ctx context.Context, drivingYears int, accidents int, usage model.BonusMalusUsage) (int, error) {

	return 0, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
